### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ZenPs** [layeh/barnard#15]
Hi, so i have a raspberry 2 but i'm not able to install it. I want to have this so i can autostart the client at boot and autoconnect it to my local raspberry server (another rasp). Could you guys please give me all the links to install it? Thanks

**Comment by njaxx** [comment]
#6 has some guidelines.  It's good that this is at the top of the issue stack, it should probably get moved into the readme if the maintainer returns.

**Comment by bontibon** [comment]
dupe of #6
