### ISSUE TITLE
compilation terminated error when installing

### ISSUE THREAD

**Issue by njaxx** [layeh/barnard#16]
I get this message when trying to install.  I know nothing about go other than hello world which confused me to the extent that I stopped investing time in picking up go and switched to android development as my primary time sink  ¯\\\_(ツ)\_/¯
 
```
$ go get -u github.com/layeh/barnard/cmd/barnard
# github.com/timshannon/go-openal/openal
In file included from dev/go/src/github.com/timshannon/go-openal/openal/alcCore.go:24:0:
local.h:5:18: fatal error: AL/al.h: No such file or directory
 #include<AL/al.h>
                  ^
compilation terminated.
```

Thanks for any tips.

**Comment by bontibon** [comment]
You need to have OpenAL development library and headers installed.

Installing on Ubuntu:
```
sudo apt install libopenal-dev
```

**Comment by njaxx** [comment]
Worked, thanks!
