### ISSUE TITLE
new issue updating/installing

### ISSUE THREAD

**Issue by derekbarnett** [layeh/barnard#26]
I don't know whether this is related, but I just upgraded to Debian stitch. An issue was introduced that I'm trying to sort out, and I attempted to upgrade barnard via the command in the readme. I don't think barnard is the problem in that chain, I was updating it in an attempt to narrow down the problem. 

As near as I can tell, my install from April 12th is working as it was before the system update to stitch. I have tried updating the existing install, as well as a fresh install into a new directory (and yes, I did point the go path at the new install directory). The new install attempt just gets me the src and pkg directories and no bin directory.

**Comment by bontibon** [comment]
Try the following update command:

```
go get -u layeh.com/barnard/cmd/barnard
```

**Comment by derekbarnett** [comment]
That did the trick.
