### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by paddyhughes** [layeh/barnard#33]
Hi,

I am having issues with installing 
Now as root again (sudo -i), edit /etc/systemd/system/mumble.service appending -username USERNAME_TO_REGISTER -certificate /home/mumble/mumble.pem at the end of ExecStart = /home/mumble/bin/talkiepi

```[Unit]
Description = Mumble Client  
Requires = systemd-user-sessions.service network.target sound.target
After = multi-user.target

[Service]
User = mumble  
Group = mumble  
Type = simple  
ExecStart = /home/mumble/bin/talkiepi -username test -certificate /home/mumble/mumble.pem  -server 192.168.1.1:64738
Restart = on-abort  
RestartSec = 5

[Install]
WantedBy = multi-user.target```

Is this correct also if i use nano to edit said i don't have permissions 

Thanks for any help given

**Comment by bontibon** [comment]
[talkiepi](https://github.com/dchote/talkiepi) is not my project.

**Comment by paddyhughes** [comment]
Sorry about that every time i go to type an issue i end back up in your project. cant find were to post for Talkiepi
