### ISSUE TITLE
Installation on Ubuntu 17.10 broken

### ISSUE THREAD

**Issue by MPW1412** [layeh/barnard#35]
Hello,

the installation process doesn't work anymore. Does someone know how to fix this?

```
$ go get -u layeh.com/barnard
# github.com/timshannon/go-openal/openal
In file included from go/src/github.com/timshannon/go-openal/openal/alcCore.go:24:0:
./local.h:5:9: fatal error: AL/al.h: No such file or directory
 #include<AL/al.h>
         ^~~~~~~~~
compilation terminated.
```

Thanks for reading.

Bye,
Matthias

**Comment by jackmawer** [comment]
Hi,

This issue was already created for #18 and can be fixed on a debian-like system such as Ubuntu with the command `sudo apt-get install libopenal1 libopenal-dev`

Thanks,
Jack
