### ISSUE TITLE
mumble server & barnard: x509 certificate...

### ISSUE THREAD

**Issue by TMInnovations** [layeh/barnard#37]
First: Thank you for sharing the possibility to have a command line based mumble client!

Machine: Raspberry Pi 3B+ with Stretch
What i did so far:
Installed Mumble Server:
```
$ sudo apt-get install mumble-server
$ sudo dpkg-reconfigure mumble-server // with autostart --> yes, higher priority --> yes, passw...
```
Then i installed the required dev libs for barnard like:
`$ sudo apt-get install golang libopus-dev libopenal-dev`
and installed barnard with
```
$ export GOPATH=$HOME/go
$ go get -u layeh.com/barnard
```
ALL on THE SAME MACHINE (because thats what I'm after ;-) )

When i try to start barnard with
`$ ./go/bin/barnard`
, I'm getting an error like
`x509: certificate is valid for Murmur Autogenerated Certificate v2, not localhost`

My thoughts are:
1.  no server certificate?
2.  no client certificate?

I read about a similar problem over here [https://github.com/layeh/gumble/issues/4](https://github.com/layeh/gumble/issues/4), so I think there's no server certificate, or probably just a not trusted one.

At this point I of course tried to find a way to install a certificate or to sign one myself. I just don't really know how to do that and where to find a way to do it. I tried to connect my phone to the mumble-server and the mumble client asked me, if I wanna trust the server certificate. I hit "Install" and everything worked. 

So my question probably is more like:
1. How can I get that error away
2. Do I have to get a certificate (maybe from lets encrypt) and HOW?
3. How Do I sign my own certificates for Mumble, so that barnard trusts them or even asks me for trusting it.

**Comment by ghost** [comment]
Run barnard with the `--insecure` flag to skip TLS verification;

```shell
$ ./go/bin/barnard --insecure
```

**Comment by TMInnovations** [comment]
Ok that worked very well 👍 Thou I want to provide encryption to the tool and don't really know where to start. Maybe you can give me a hint?

**Comment by ghost** [comment]
If you're running the server locally, there would be no point in securing the connection, as the data is never leaving your machine.

If, however, you want to setup a valid certificate for your server anyway, you could:

- create your own root certificate, then
- create a certificate and key for the server that is signed by the root certificate, then finally
- trust the root certificate on your client

While you could do that using openssl commands, I prefer using a GUI tool called [xca](https://hohnstaedt.de/xca/).

**Comment by TMInnovations** [comment]
Thank you so much! I will try that!
